CREATE TABLE BookCopy (
ISBN TEXT 
NOT NULL,
copyNumber INTEGER NOT NULL,
daysLoaned INTEGER,
CONSTRAINT fk FOREIGN KEY (ISBN) REFERENCES BookEdition (ISBN),
CONSTRAINT pk PRIMARY KEY (ISBN,copyNumber)
);